// SPDX-License-Identifier: MIT
// Shadow SE - fetcher implementations: deterministic stub + libcurl.
#include "shadowse/fetcher.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>

#ifdef HAVE_CURL
#include <curl/curl.h>
#include <mutex>
#endif

// ---------------------------------------------------------------------------
// StubFetcher - deterministic offline HTML generation.
// ---------------------------------------------------------------------------

namespace shadowse {

namespace {

std::string stubHost(const std::string& url) {
    const std::size_t scheme = url.find("://");
    const std::size_t start = scheme == std::string::npos ? 0 : scheme + 3;
    const std::size_t end = url.find('/', start);
    return url.substr(start, end == std::string::npos ? std::string::npos : end - start);
}

} // namespace

FetchResult StubFetcher::fetch(const std::string& url) {
    // Serve a permissive robots.txt so the crawler's compliance check works
    // offline without a real network.
    const std::size_t rp = url.rfind("robots.txt");
    const bool isRobots =
        rp != std::string::npos && (rp == 0 || url[rp - 1] == '/' || url[rp - 1] == '?');
    if (isRobots) {
        FetchResult result;
        result.ok = true;
        result.html = "User-agent: *\nAllow: /\n";
        return result;
    }

    const std::string host = stubHost(url);
    const std::string safeHost = host.empty() ? "unknown" : host;

    std::ostringstream html;
    html << "<!DOCTYPE html>\n<html><head>\n"
         << "  <title>Stub Index: " << safeHost << "</title>\n"
         << "  <meta name=\"description\" content=\"Sample stub document for "
         << url << " generated by the Shadow SE offline fetcher.\">\n"
         << "</head><body>\n"
         << "  <h1>" << safeHost << "</h1>\n"
         << "  <p>This deterministic sample page was produced by the Shadow SE stub "
         << "fetcher. It contains indexable telemetry text about " << safeHost
         << " and the shadow search engine index compression pipeline.</p>\n"
         << "  <p>References: inverted index, bm25 ranking, tor routing, onion "
         << "hidden services, sandbox parsing and threat intelligence feeds.</p>\n"
         << "  <a href=\"/docs/a\">Document A</a>\n"
         << "  <a href=\"/docs/b\">Document B</a>\n"
         << "  <a href=\"https://" << safeHost << "/mirror\">Mirror</a>\n"
         << "</body></html>\n";

    FetchResult result;
    result.ok = true;
    result.html = html.str();
    return result;
}

} // namespace shadowse

// ---------------------------------------------------------------------------
// CurlFetcher - libcurl backed (only when HAVE_CURL is defined).
// ---------------------------------------------------------------------------

#ifdef HAVE_CURL

#include <curl/curl.h>

#include <chrono>
#include <mutex>
#include <thread>

namespace shadowse {

namespace {

std::once_flag g_curlInitFlag;

std::size_t writeCallback(char* ptr, std::size_t size, std::size_t nmemb, void* userdata) {
    auto* out = static_cast<std::string*>(userdata);
    const std::size_t bytes = size * nmemb;
    out->append(ptr, bytes);
    return bytes;
}

// Transport/proxy failures are retryable (failover); HTTP-level and
// protocol-level errors are not.
bool isTransientCurlError(CURLcode code) {
    switch (code) {
        case CURLE_COULDNT_CONNECT:
        case CURLE_COULDNT_RESOLVE_PROXY:
        case CURLE_OPERATION_TIMEDOUT:
        case CURLE_SEND_ERROR:
        case CURLE_RECV_ERROR:
        case CURLE_PROXY:
        case CURLE_HTTP2:
            return true;
        default:
            return false;
    }
}

} // namespace

CurlFetcher::CurlFetcher(std::shared_ptr<TorProxyManager> manager, long timeoutMs)
    : manager_(std::move(manager)), timeoutMs_(timeoutMs) {
    std::call_once(g_curlInitFlag, [] { curl_global_init(CURL_GLOBAL_DEFAULT); });
}

CurlFetcher::~CurlFetcher() = default;

FetchResult CurlFetcher::fetch(const std::string& url) {
    FetchResult result;
    const bool onion = url.find(".onion") != std::string::npos;
    const std::size_t maxTries = manager_ ? 1 + manager_->maxRetries(url) : 1;

    for (std::size_t attempt = 0; attempt < maxTries; ++attempt) {
        if (attempt > 0 && manager_) {
            std::this_thread::sleep_for(manager_->backoff(attempt - 1));
        }

        TorEndpoint ep;
        if (manager_) {
            ep = manager_->selectProxy(url);
        }
        const std::string proxy = (ep.host.empty() || ep.port == 0) ? "" : socks5Url(ep);
        if (onion && proxy.empty()) {
            result.error =
                "onion target requires Tor; no healthy SOCKS5 proxy available (run 'status')";
            break;  // not retryable without a proxy
        }

        CURL* curl = curl_easy_init();
        if (curl == nullptr) {
            result.error = "curl_easy_init() failed";
            break;
        }
        std::string body;
        char errbuf[CURL_ERROR_SIZE] = {0};
        const auto start = std::chrono::steady_clock::now();

        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 5L);
        curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, timeoutMs_);
        curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, timeoutMs_ / 2);
        curl_easy_setopt(curl, CURLOPT_USERAGENT,
                         "Mozilla/5.0 (compatible; ShadowSE/1.0; +https://github.com/alhassanshehade/shadow-se)");
        curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "");
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &body);
        curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);

        if (!proxy.empty()) {
            curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str());
            // SOCKS5 username/password = Tor stream isolation (fresh circuit
            // per isolation token).
            if (!ep.username.empty()) {
                curl_easy_setopt(curl, CURLOPT_PROXYUSERNAME, ep.username.c_str());
                curl_easy_setopt(curl, CURLOPT_PROXYPASSWORD, ep.password.c_str());
            }
        }

        const CURLcode code = curl_easy_perform(curl);
        long httpCode = 0;
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &httpCode);
        curl_easy_cleanup(curl);
        const auto latency = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now() - start);

        if (code == CURLE_OK && httpCode < 400) {
            if (manager_ && !ep.host.empty()) {
                manager_->reportSuccess(ep.host, ep.port, latency);
            }
            result.ok = true;
            result.html = std::move(body);
            return result;
        }

        result.error = code != CURLE_OK
                           ? (errbuf[0] != '\0' ? std::string(errbuf) : curl_easy_strerror(code))
                           : "HTTP " + std::to_string(httpCode);
        if (manager_ && !ep.host.empty()) {
            manager_->reportFailure(ep.host, ep.port, result.error);
        }
        if (httpCode >= 400) {
            break;  // HTTP-level failure: not retryable
        }
        if (!isTransientCurlError(code) && !onion) {
            break;  // non-transient, non-onion failure: not retryable
        }
        // Otherwise (transient or onion): retry - the manager fails over to
        // another proxy endpoint on the next selectProxy().
    }
    return result;
}

} // namespace shadowse

#else // !HAVE_CURL

namespace shadowse {

CurlFetcher::CurlFetcher(std::shared_ptr<TorProxyManager>, long) {}

CurlFetcher::~CurlFetcher() = default;

FetchResult CurlFetcher::fetch(const std::string& url) {
    FetchResult result;
    result.error = "libcurl support was not compiled in; cannot fetch " + url;
    return result;
}

} // namespace shadowse

#endif // HAVE_CURL
