// SPDX-License-Identifier: MIT
// Shadow SE - fetcher implementations: deterministic stub + libcurl.
#include "shadowse/fetcher.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>

#ifdef HAVE_CURL
#include <curl/curl.h>
#include <mutex>
#endif

// ---------------------------------------------------------------------------
// StubFetcher - deterministic offline HTML generation.
// ---------------------------------------------------------------------------

namespace shadowse {

namespace {

std::string stubHost(const std::string& url) {
    const std::size_t scheme = url.find("://");
    const std::size_t start = scheme == std::string::npos ? 0 : scheme + 3;
    const std::size_t end = url.find('/', start);
    return url.substr(start, end == std::string::npos ? std::string::npos : end - start);
}

} // namespace

FetchResult StubFetcher::fetch(const std::string& url) {
    // Serve a permissive robots.txt so the crawler's compliance check works
    // offline without a real network.
    const std::size_t rp = url.rfind("robots.txt");
    const bool isRobots =
        rp != std::string::npos && (rp == 0 || url[rp - 1] == '/' || url[rp - 1] == '?');
    if (isRobots) {
        FetchResult result;
        result.ok = true;
        result.html = "User-agent: *\nAllow: /\n";
        return result;
    }

    const std::string host = stubHost(url);
    const std::string safeHost = host.empty() ? "unknown" : host;

    std::ostringstream html;
    html << "<!DOCTYPE html>\n<html><head>\n"
         << "  <title>Stub Index: " << safeHost << "</title>\n"
         << "  <meta name=\"description\" content=\"Sample stub document for "
         << url << " generated by the Shadow SE offline fetcher.\">\n"
         << "</head><body>\n"
         << "  <h1>" << safeHost << "</h1>\n"
         << "  <p>This deterministic sample page was produced by the Shadow SE stub "
         << "fetcher. It contains indexable telemetry text about " << safeHost
         << " and the shadow search engine index compression pipeline.</p>\n"
         << "  <p>References: inverted index, bm25 ranking, tor routing, onion "
         << "hidden services, sandbox parsing and threat intelligence feeds.</p>\n"
         << "  <a href=\"/docs/a\">Document A</a>\n"
         << "  <a href=\"/docs/b\">Document B</a>\n"
         << "  <a href=\"https://" << safeHost << "/mirror\">Mirror</a>\n"
         << "</body></html>\n";

    FetchResult result;
    result.ok = true;
    result.html = html.str();
    return result;
}

} // namespace shadowse

// ---------------------------------------------------------------------------
// CurlFetcher - libcurl backed (only when HAVE_CURL is defined).
// ---------------------------------------------------------------------------

#ifdef HAVE_CURL

namespace shadowse {

namespace {

std::once_flag g_curlInitFlag;

std::size_t writeCallback(char* ptr, std::size_t size, std::size_t nmemb, void* userdata) {
    auto* out = static_cast<std::string*>(userdata);
    const std::size_t bytes = size * nmemb;
    out->append(ptr, bytes);
    return bytes;
}

} // namespace

CurlFetcher::CurlFetcher(std::string socks5Proxy, long timeoutMs)
    : proxy_(std::move(socks5Proxy)), timeoutMs_(timeoutMs) {
    std::call_once(g_curlInitFlag, [] { curl_global_init(CURL_GLOBAL_DEFAULT); });
}

CurlFetcher::~CurlFetcher() = default;

FetchResult CurlFetcher::fetch(const std::string& url) {
    FetchResult result;
    if (proxy_.empty() && url.find(".onion") != std::string::npos) {
        result.error = "onion target requires Tor; SOCKS5 proxy is not configured (run 'status')";
        return result;
    }
    CURL* curl = curl_easy_init();
    if (curl == nullptr) {
        result.error = "curl_easy_init() failed";
        return result;
    }

    std::string body;
    char errbuf[CURL_ERROR_SIZE] = {0};

    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 5L);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, timeoutMs_);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, timeoutMs_ / 2);
    curl_easy_setopt(curl, CURLOPT_USERAGENT,
                     "Mozilla/5.0 (compatible; ShadowSE/1.0; +https://github.com/alhassanshehade/shadow-se)");
    curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "");
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &body);
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);

    if (!proxy_.empty()) {
        curl_easy_setopt(curl, CURLOPT_PROXY, proxy_.c_str());
    }

    const CURLcode code = curl_easy_perform(curl);
    long httpCode = 0;
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &httpCode);
    curl_easy_cleanup(curl);

    if (code != CURLE_OK) {
        result.error = errbuf[0] != '\0' ? std::string(errbuf) : curl_easy_strerror(code);
        return result;
    }
    if (httpCode >= 400) {
        result.error = "HTTP " + std::to_string(httpCode);
        return result;
    }

    result.ok = true;
    result.html = std::move(body);
    return result;
}

} // namespace shadowse

#else // !HAVE_CURL

namespace shadowse {

CurlFetcher::CurlFetcher(std::string, long) {}

CurlFetcher::~CurlFetcher() = default;

FetchResult CurlFetcher::fetch(const std::string& url) {
    FetchResult result;
    result.error = "libcurl support was not compiled in; cannot fetch " + url;
    return result;
}

} // namespace shadowse

#endif // HAVE_CURL
